Try to add init containers. Try to test with all directories

diff --git a/argo_cd_helm/trembita-1.12.6-ss/templates/init-containers.yaml b/argo_cd_helm/trembita-1.12.6-ss/templates/init-containers.yaml
--- a/argo_cd_helm/trembita-1.12.6-ss/templates/init-containers.yaml
+++ b/argo_cd_helm/trembita-1.12.6-ss/templates/init-containers.yaml
@@ -1,38 +1,39 @@
 {{- define "trembita-1.12.6-ss.initContainers" }}
-initContainers:
-  {{- range $name, $cfg := .Values.persistentVolumes }}
-  {{- if and $cfg.enabled (or (not (hasKey $cfg "initCopy")) $cfg.initCopy) }}
-  - name: init-copy-{{ $name }}
-    image: {{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
-    command: ["/bin/sh", "-c"]
-    args:
-      - |
-        set -x
-        echo "[INFO] Starting init container for {{ $name }}"
-        if [ -d "{{ $cfg.mountPath }}" ]; then
-          cp -rp {{ $cfg.mountPath }}/* /mnt/target/ || true
-          echo "[INFO] Done copying {{ $cfg.mountPath }} to /mnt/target/"
-        else
-          echo "[WARN] Source directory {{ $cfg.mountPath }} not found"
-        fi
-    volumeMounts:
-      - name: {{ $name }}
-        mountPath: /mnt/target
-  {{- end }}
-  {{- end }}
-{{- end }}
-
 {{/*initContainers:*/}}
-{{/*  - name: etcuxp*/}}
+{{/*  {{- range $name, $cfg := .Values.persistentVolumes }}*/}}
+{{/*  {{- if and $cfg.enabled (or (not (hasKey $cfg "initCopy")) $cfg.initCopy) }}*/}}
+{{/*  - name: init-copy-{{ $name }}*/}}
 {{/*    image: {{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}*/}}
-{{/*    command: ["/bin/sh","-c"]*/}}
+{{/*    command: ["/bin/sh", "-c"]*/}}
 {{/*    args:*/}}
 {{/*      - |*/}}
 {{/*        set -x*/}}
-{{/*        echo "Start copy"*/}}
-{{/*        cp -rp /etc/uxp/* /mnt/etc-uxp/*/}}
-{{/*        chown uxp:uxp /mnt/etc-uxp/*/}}
-{{/*        echo "End copy"*/}}
+{{/*        echo "[INFO] Starting init container for {{ $name }}"*/}}
+{{/*        if [ -d "{{ $cfg.mountPath }}" ]; then*/}}
+{{/*          cp -rp {{ $cfg.mountPath }}/* /mnt/target/ || true*/}}
+{{/*          echo "[INFO] Done copying {{ $cfg.mountPath }} to /mnt/target/"*/}}
+{{/*        else*/}}
+{{/*          echo "[WARN] Source directory {{ $cfg.mountPath }} not found"*/}}
+{{/*        fi*/}}
 {{/*    volumeMounts:*/}}
-{{/*      - name: etc-uxp*/}}
-{{/*        mountPath: /mnt/etc-uxp/*/}}
+{{/*      - name: {{ $name }}*/}}
+{{/*        mountPath: /mnt/target*/}}
+{{/*  {{- end }}*/}}
+{{/*  {{- end }}*/}}
+{{/*{{- end }}*/}}
+
+initContainers:
+  - name: etcuxp
+    image: {{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}
+    command: ["/bin/sh","-c"]
+    args:
+      - |
+        set -x
+        echo "Start copy"
+        cp -rp /etc/uxp/* /mnt/etc-uxp/
+        chown uxp:uxp /mnt/etc-uxp/
+        echo "End copy"
+    volumeMounts:
+      - name: etc-uxp
+        mountPath: /mnt/etc-uxp/
+{{- end }}
